-- 쇼핑몰 DB 연습문제

1. 카테고리 테이블 (CATEGORIES)

카테고리 ID (CATEGORY_ID) - NUMBER [PK]
카테고리 이름 (CATEGORY_NAME) - VARCHAR2(100) [UNIQUE]
 
 
 
2. 상품 정보 테이블 (PRODUCTS)

상품 코드 (PRODUCT_ID) - NUMBER [PK]
상품 이름 (PRODUCT_NAME) - VARCHAR2(100) [NOT NULL]
카테고리 (CATEGORY) - NUMBER [FK - CATEGORIES(CATEGORY_ID)]
가격 (PRICE) - NUMBER [DEFAULT 0]
재고량 (STOCK_QUANTITY) NUMBER [DEFAULT 0]



3. 고객 정보 테이블 (CUSTOMERS)

고객 ID (CUSTOMER_ID) - NUMBER [PK]
이름 (NAME) - VARCHAR2(20) [NOT NULL]
성별 (GENDER) - CHAR(3) [CHECK 남, 여]
주소 (ADDRESS) - VARCHAR2(100)  
전화번호 (PHONE) - VARCHAR2(30)




4. 주문 정보 테이블 (ORDERS)

주문 번호 (ORDER_ID) - NUMBER [PK]
고객 ID (CUSTOMER_ID) - NUMBER [FK - CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE]
주문일 (ORDER_DATE) - DATE [DEFAULT SYSDATE]
처리상태 (STATUS) - CHAR(1) [CHECK ('Y', 'N') DEFAULT 'N']




5. 주문 상세 정보 테이블 (ORDER_DETAILS)

주문 상세 ID (ORDER_DETAIL_ID) - NUMBER [PK]
주문 번호 (ORDER_ID) NUMBER - [FK - ORDERS(ORDER_ID) ON DELETE CASCADE]
상품 코드 (PRODUCT_ID) NUMBER - [FK - PRODUCTS(PRODUCT_ID) ON DELETE SET NULL]
수량 (QUANTITY) NUMBER
가격 (PRICE_PER_UNIT) NUMBER

-------------------쇼핑몰 연습문제-----------------------------


CREATE TABLE "CATEGORIES" (
 CATEGORY_ID NUMBER PRIMARY KEY,
 CATEGORY_NAME VARCHER2(100), UNIQUE, CATEGORY
 
 CO
 



);


